import { describe, it, expect } from "vitest";
import { formatPrComment } from "../../src/cli/commands/report.js";
import type { NormalizedReportSummary } from "../../src/cli/commands/report.js";

describe("formatPrComment", () => {
  const baseSummary: NormalizedReportSummary = {
    adapter: "vitest",
    totals: {
      total: 457,
      passed: 455,
      failed: 1,
      flaky: 1,
      skipped: 0,
      retries: 2,
      durationMs: 16000,
    },
    files: [
      {
        suite: "tests/api.test.ts",
        totals: { total: 50, passed: 49, failed: 1, flaky: 0, skipped: 0, retries: 0, durationMs: 3000 },
      },
    ],
    unstable: [
      {
        testId: "t1",
        suite: "tests/api.test.ts",
        testName: "handles timeout",
        taskId: "tests/api.test.ts",
        filter: null,
        variant: null,
        status: "failed",
        durationMs: 500,
        retryCount: 0,
      },
      {
        testId: "t2",
        suite: "tests/db.test.ts",
        testName: "concurrent write",
        taskId: "tests/db.test.ts",
        filter: null,
        variant: null,
        status: "flaky",
        durationMs: 200,
        retryCount: 2,
      },
    ],
    tests: [],
  };

  it("includes header and results table", () => {
    const output = formatPrComment(baseSummary);
    expect(output).toContain("## flaker: Test Report");
    expect(output).toContain("| Passed | 455 |");
    expect(output).toContain("| Failed | 1 |");
  });

  it("lists failures in Failures section", () => {
    const output = formatPrComment(baseSummary);
    expect(output).toContain("### Failures");
    expect(output).toContain("handles timeout");
  });

  it("lists flaky tests in Flaky section", () => {
    const output = formatPrComment(baseSummary);
    expect(output).toContain("### Flaky");
    expect(output).toContain("concurrent write");
  });

  it("omits Failures and Flaky sections when none", () => {
    const clean: NormalizedReportSummary = {
      ...baseSummary,
      totals: { ...baseSummary.totals, failed: 0, flaky: 0 },
      unstable: [],
    };
    const output = formatPrComment(clean);
    expect(output).not.toContain("### Failures");
    expect(output).not.toContain("### Flaky");
  });

  it("includes footer", () => {
    const output = formatPrComment(baseSummary);
    expect(output).toContain("Generated by");
    expect(output).toContain("flaker");
  });
});
